import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { UserContextProvider } from "@/contexts/UserContext";
import { DarkModeContextProvider } from "@/contexts/DarkMode";
import { EventsContextProvider } from "@/contexts/EventsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gelianthus Tries NextJS #03",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="/sunflower_logo.webp"
					sizes="any"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
					rel="stylesheet"
				/>
			</head>
			<body className={inter.className}>
				<Provider>
					<UserContextProvider>
						<EventsContextProvider>
							<DarkModeContextProvider>{children}</DarkModeContextProvider>
						</EventsContextProvider>
					</UserContextProvider>
				</Provider>
			</body>
		</html>
	);
}
